# Generated by Django 3.2.7 on 2022-06-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220626_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='top_agent',
        ),
        migrations.AddField(
            model_name='profile',
            name='top_seller',
            field=models.BooleanField(default=False, verbose_name='Top Seller'),
        ),
    ]
