# Generated by Django 3.2.7 on 2022-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220626_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='top_seller',
        ),
        migrations.AddField(
            model_name='profile',
            name='top_agent',
            field=models.BooleanField(default=False, verbose_name='Top agent'),
        ),
    ]
