# Generated by Django 3.2.7 on 2022-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220626_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='top_seller',
            field=models.BooleanField(default=False, verbose_name='Top seller'),
        ),
    ]
