# Generated by Django 3.2.7 on 2022-06-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_top_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='top_seller',
        ),
    ]
