# Generated by Django 3.2.7 on 2022-06-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover_photo',
            field=models.ImageField(blank=True, default='properties/house_sample.jpg', null=True, upload_to='properties/', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo1',
            field=models.ImageField(blank=True, default='properties/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo2',
            field=models.ImageField(blank=True, default='properties/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo3',
            field=models.ImageField(blank=True, default='properties/interior_sample.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo4',
            field=models.ImageField(blank=True, default='properties/interior_sample.jpg', null=True, upload_to=''),
        ),
    ]
